### PR TITLE
feat: support shared VPC with allow_public_egress

### LINKED ISSUE #173: Support deployment to shared VPC
### TL;DR

Most of the implementation seems to work with shared VPC except for the NAT resources when `alllow_public_egress` is true.  To support shared VPC the resources `vault-router` (`google_compute_router`) and `vault-nat` (`google_compute_router_nat` and `google_compute_address`) would need to be created in the shared VPC host project (see [here](https://cloud.google.com/nat/docs/overview#interaction-shared-vpc)).  This can be implemented by adding a new variable (`host_project_id`) that when set indicates a shared VPC deployment and would be used in the creation of the mentioned resources

### Terraform Resources

```markdown
resource "google_compute_address" "vault-nat" {
  count   = var.allow_public_egress ? 2 : 0
  project = var.project_id
  name    = "vault-nat-external-${count.index}"
  region  = var.region

  depends_on = [google_project_service.service]
}

resource "google_compute_router" "vault-router" {
  count   = var.allow_public_egress ? 1 : 0
  name    = "vault-router"
  project = var.project_id
  region  = var.region
  network = local.network

  bgp {
    asn = 64514
  }

  depends_on = [google_project_service.service]
}

resource "google_compute_router_nat" "vault-nat" {
  count   = var.allow_public_egress ? 1 : 0
  name    = "vault-nat-1"
  project = var.project_id
  router  = google_compute_router.vault-router[0].name
  region  = var.region

  nat_ip_allocate_option = "MANUAL_ONLY"
  nat_ips                = google_compute_address.vault-nat.*.self_link

  source_subnetwork_ip_ranges_to_nat = "LIST_OF_SUBNETWORKS"

  subnetwork {
    name                    = local.subnet
    source_ip_ranges_to_nat = ["PRIMARY_IP_RANGE"]
  }

  depends_on = [google_project_service.service]
}
```

### Detailed design

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ggprod**
Closes #173 

When using allow_public_egress with shared VPC the Cloud NAT resources need to be in the host project.  This PR adds that enhancement/fix.  It also fixes the firewall rules in the case of a shared VPC deployment (by creating them in the host project as is necessary in that case)

Also adds a new variable user_vault_config that is appended to the vault config in the config.hcl.tpl template

### CODE REVIEW

**Comment by ggprod** [comment]
@cft-admins could I get a /gcbrun?  Thanks!

**Comment by apeabody** [comment]
Thanks for the contribution @ggprod, from the LINT:

```
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/README.md /tmp/tmp.7OFOl7jETz/generate_docs/workspace/README.md
177a178
> | host\_project\_id | The project id of the shared VPC host project, when deploying into a shared VPC | `string` | `""` | no |
187d187
< | host\_project\_id | ID of the host project for shared VPC when deploying into a shard VPC. | `string` | `""` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
```

**Comment by ggprod** [comment]
> Thanks for the contribution @ggprod, from the LINT:
> 
> ```
> Checking for documentation generation
> diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/README.md /tmp/tmp.7OFOl7jETz/generate_docs/workspace/README.md
> 177a178
> > | host\_project\_id | The project id of the shared VPC host project, when deploying into a shared VPC | `string` | `""` | no |
> 187d187
> < | host\_project\_id | ID of the host project for shared VPC when deploying into a shard VPC. | `string` | `""` | no |
> Error: Documentation generation has not been run, please run the
> 'make docker_generate_docs' command and commit the above changes.
> ```

done, could I get another /gcbrun please?  Thanks!

**Comment by ggprod** [comment]
@ctf-admins I discovered a problem with the firewall rules when using a shared_vpc and fixed it.  could I get another /gcbrun?  Thanks!

**Comment by ggprod** [comment]
@ctf-admins I added an extra variable that allows the user to provide extra vault configuration (which would allow configuring the vault instance for prometheus metrics for example)... could I get another /gcbrun?  Thanks!

**Review by apeabody — COMMENTED** [review]
@bharathkkb or @g-awmalik  - Can I get your review on this method? https://github.com/terraform-google-modules/terraform-google-vault/pull/174/files#diff-7a72e6f6555ca3f4aa2fb5d35f310c6be101981ed1ac7cc03dfe6f2907d1a73eR76

**Comment by ggprod** [comment]
@apeabody any chance this could be approved and merged?

**Comment by apeabody** [comment]
> @apeabody any chance this could be approved and merged?

Hi @ggprod - I just triggered the CI and will review with @bharathkkb

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @ggprod!

**Pull request merged**
