### PR TITLE
Fixed service_account_project_iam_roles variable usage

### PR DESCRIPTION
**Pull request by MKaciuba**

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR @MKaciuba 
Could you sign the CLA https://github.com/terraform-google-modules/terraform-google-vault/pull/138/checks?check_run_id=4807043249

**Comment by michal-billtech** [comment]
@bharathkkb just signed.

**Comment by michal-billtech** [comment]
@bharathkkb pls run the checks again. It should work this time.

**Comment by bharathkkb** [comment]
@michal-billtech It looks like you are using a different GH account? It seems to be failing at that
```
❌ d42e906 PR Opener: @MKaciuba
✅ d42e906 Author: @michal-billtech <mi***l​@billtech.pl>
```

**Pull request closed without merging**
