### PR TITLE
fix some shellcheck errors

### PR DESCRIPTION
**Pull request by Andor**

### CODE REVIEW

**Comment by sethvargo** [comment]
Hey @Andor - thank you for the PR. I'm in favor of all these changes, but I'd prefer to leave out the shellcheck ignore directives.

**Comment by Andor** [comment]
Yeah, I like to remove all the ignores, but unfortunately shellcheck itself has no support to mark variables as "external"  yet :( https://github.com/koalaman/shellcheck/issues/356
With that issue fixed we will have only a couple of ignores in the script: that one about "unused" variable, which is used in form `$$LOCAL_IP` and another about "source ..." files.

In the other hand, you have no CI with shellcheck in this project, so I can remove all the ignores from the PR and keep only changes which don't require ignores.

**Comment by sethvargo** [comment]
Yea, let's do that for now please 😄

**Comment by sethvargo** [comment]
Thanks!

**Pull request merged**
