### PR TITLE
fix: Add iam permission required for vault version greater than 1.11 …

### PR DESCRIPTION
**Pull request by dcb-imvaria**
…(#184)

### CODE REVIEW

**Comment by airman604** [comment]
I also experienced the same issue trying to install Vault 1.16 and the proposed fix resolved the issue. Per https://support.hashicorp.com/hc/en-us/articles/5277291261075-Auto-unseal-using-GCP-Cloud-KMS#:~:text=2.-,credentials,-%3A%20This%20parameter only `cloudkms.cryptoKeys.get` permission is needed, but I think considering it's a key dedicated to Vault, using viewer is reasonable.

**Comment by dcb-imvaria** [comment]
The workflow is awaiting approval from the maintainer. Is a maintainer assigned?

**Comment by ianc769** [comment]
+1 and maybe @g-awmalik or @apeabody ?

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @dcb-imvaria!

**Pull request merged**
